#ifndef PROTOCOL_SHADE_H_
#define PROTOCOL_SHADE_H_

#include <stdint.h>

enum {
	SHADE_VERSION_MAJOR = (uint16_t) 1,
	SHADE_VERSION_MINOR = (uint16_t) 3,
};

enum {
	SHADE_VERSION_MAJOR_POS = 8,
	SHADE_VERSION_MAJOR_MASK = 0xFF << SHADE_VERSION_MAJOR_POS,
	SHADE_VERSION_MINOR_POS = 0,
	SHADE_VERSION_MINOR_MASK = 0xFF << SHADE_VERSION_MINOR_POS,
	SHADE_VERSION = SHADE_VERSION_MAJOR << SHADE_VERSION_MAJOR_POS | SHADE_VERSION_MINOR << SHADE_VERSION_MINOR_POS,
};

enum {
	SHADE_PTID_ACK = 0xFFF0,
	SHADE_PTID_NACK = 0xFFF1,
	SHADE_PTID_SHADE_VERSION_REQUEST = 0xFFF2,
	SHADE_PTID_SHADE_VERSION_REPLY = 0xFFF3,
	SHADE_PTID_PACKET_REPEAT_REQUEST = 0xFFF4,
	SHADE_PTID_PACKET_MODE_DENIED = 0xFFF5,
	SHADE_PTID_SUPPORTED_MODE_REQUEST = 0xFFF6,
	SHADE_PTID_SUPPORTED_MODE_REPLY = 0xFFF7,
	SHADE_PTID_MAX_MSG_LENGTH_REQUEST = 0xFFF8,
	SHADE_PTID_MAX_MSG_LENGTH_REPLY = 0xFFF9,
	SHADE_PTID_RESERVED10 = 0xFFFA,
	SHADE_PTID_RESERVED11 = 0xFFFB,
	SHADE_PTID_RESERVED12 = 0xFFFC,
	SHADE_PTID_RESERVED13 = 0xFFFD,
	SHADE_PTID_RESERVED14 = 0xFFFE,
	SHADE_PTID_RESERVED15 = 0xFFFF,

	SHADE_PTID_SHM_ACK = 0xF0,
	SHADE_PTID_SHM_NACK = 0xF1,
	SHADE_PTID_SHM_SHADE_VERSION_REQUEST = 0xF2,
	SHADE_PTID_SHM_SHADE_VERSION_REPLY = 0xF3,
	SHADE_PTID_SHM_PACKET_REPEAT_REQUEST = 0xF4,
	SHADE_PTID_SHM_PACKET_MODE_DENIED = 0xF5,
	SHADE_PTID_SHM_SUPPORTED_MODE_REQUEST = 0xF6,
	SHADE_PTID_SHM_SUPPORTED_MODE_REPLY = 0xF7,
	SHADE_PTID_SHM_MAX_MSG_LENGTH_REQUEST = 0xF8,
	SHADE_PTID_SHM_MAX_MSG_LENGTH_REPLY = 0xF9,
	SHADE_PTID_SHM_RESERVED10 = 0xFA,
	SHADE_PTID_SHM_RESERVED11 = 0xFB,
	SHADE_PTID_SHM_RESERVED12 = 0xFC,
	SHADE_PTID_SHM_RESERVED13 = 0xFD,
	SHADE_PTID_SHM_RESERVED14 = 0xFE,
	SHADE_PTID_SHM_RESERVED15 = 0xFF,

};

enum {
	SHADE_SIZE_0 = 0,
	SHADE_SIZE_1 = 1,
	SHADE_SIZE_2 = 2,
	SHADE_SIZE_4 = 3,

	SHADE_PFC_PISCS_POS = 0, //Packet in-session counter value size
	SHADE_PFC_PISCS_MASK = 0x03 << SHADE_PFC_PISCS_POS,

	SHADE_PFC_PDSS_POS = 2, //Packet size value size
	SHADE_PFC_PDSS_MASK = 0x03 << SHADE_PFC_PDSS_POS,

	SHADE_PFC_PCSS_POS = 4, //Packet checksum value size
	SHADE_PFC_PCSS_MASK = 0x03 << SHADE_PFC_PCSS_POS,

	SHADE_PFC_SHM_POS = 6, //Short header mode
	SHADE_PFC_SHM_MASK = 0x01 << SHADE_PFC_SHM_POS,
	SHADE_PFC_SHM = 1 << SHADE_PFC_SHM_POS,

	SHADE_PFC_RESERVED0_POS = 7,
	SHADE_PFC_RESERVED0_MASK = 0x01,
	SHADE_PFC_RESERVED0 = 0x01 << SHADE_PFC_RESERVED0_POS,

	SHADE_MODE_0000 = 0,
	SHADE_MODE_0001 = SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0002 = SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0004 = SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0010 = SHADE_SIZE_1 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0011 = SHADE_SIZE_1 << SHADE_PFC_PDSS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0012 = SHADE_SIZE_1 << SHADE_PFC_PDSS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0014 = SHADE_SIZE_1 << SHADE_PFC_PDSS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0020 = SHADE_SIZE_2 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0021 = SHADE_SIZE_2 << SHADE_PFC_PDSS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0022 = SHADE_SIZE_2 << SHADE_PFC_PDSS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0024 = SHADE_SIZE_2 << SHADE_PFC_PDSS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0040 = SHADE_SIZE_4 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0041 = SHADE_SIZE_4 << SHADE_PFC_PDSS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0042 = SHADE_SIZE_4 << SHADE_PFC_PDSS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0044 = SHADE_SIZE_4 << SHADE_PFC_PDSS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,

	SHADE_MODE_0100 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS,
	SHADE_MODE_0101 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0102 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0104 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0110 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0111 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0112 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0114 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0120 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0121 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0122 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0124 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0140 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0141 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0142 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0144 = SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,

	SHADE_MODE_0200 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS,
	SHADE_MODE_0201 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0202 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0204 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0210 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0211 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0212 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0214 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0220 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0221 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0222 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0224 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0240 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0241 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0242 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0244 = SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,

	SHADE_MODE_0400 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS,
	SHADE_MODE_0401 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0402 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0404 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0410 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0411 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0412 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0414 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0420 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0421 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0422 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0424 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0440 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_0441 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0442 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_0444 = SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,

	SHADE_MODE_1000 = SHADE_PFC_SHM,
	SHADE_MODE_1001 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1002 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1004 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1010 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1011 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1012 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1014 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1020 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1021 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1022 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1024 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1040 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1041 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1042 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1044 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,

	SHADE_MODE_1100 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS,
	SHADE_MODE_1101 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1102 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1104 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1110 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1111 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1112 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1114 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1120 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1121 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1122 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1124 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1140 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1141 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1142 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1144 = SHADE_PFC_SHM | SHADE_SIZE_1 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,

	SHADE_MODE_1200 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS,
	SHADE_MODE_1201 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1202 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1204 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1210 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1211 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1212 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1214 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1220 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1221 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1222 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1224 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1240 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1241 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1242 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1244 = SHADE_PFC_SHM | SHADE_SIZE_2 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,

	SHADE_MODE_1400 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS,
	SHADE_MODE_1401 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1402 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1404 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1410 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1411 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1412 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1414 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_1 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1420 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1421 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1422 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1424 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_2 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1440 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS,
	SHADE_MODE_1441 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_1 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1442 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_2 << SHADE_PFC_PCSS_POS,
	SHADE_MODE_1444 = SHADE_PFC_SHM | SHADE_SIZE_4 << SHADE_PFC_PISCS_POS | SHADE_SIZE_4 << SHADE_PFC_PDSS_POS
			| SHADE_SIZE_4 << SHADE_PFC_PCSS_POS,

};

typedef struct __attribute__((packed)) {
	//WARNING! Real object structure is configurable, this object
	//doesn't represent all headers
	uint8_t PFC; //Packet Flow Control. The only fixed position and size element.
	uint8_t PSID; //Packet Session ID. Absent in short header mode.
	uint8_t PTIDL; //Packet Type ID Low Byte.
	uint8_t PTIDH; //Packet Type ID High Byte. Absent in short header mode.
	uint32_t PISC; //Packet In-session Counter. 0, 1, 2 or 4 bytes.
	uint32_t PDS; //Payload Data Size. 0, 1, 2 or 4 bytes.
	uint32_t PCS; //Packet Checksum. 0, 1, 2 or 4 bytes.
	//Packet checksum incl. header, checksum field treated as zeroes for checksum calculation
} shade_header;

#ifdef __cplusplus
extern "C" {
#endif

uint8_t shade_header_size_get(shade_header *header);
uint32_t shade_packet_size_get(shade_header *header);
uint32_t shade_payload_size_get(shade_header *header);
uint8_t* shade_payload_get(shade_header *header); //start of payload, nullptr if not present
uint8_t shade_mode_get(shade_header *header);

uint8_t shade_pfc_get(shade_header *header); //flow control flags
uint8_t shade_psid_get(shade_header *header); // [0..255]
uint16_t shade_ptid_get(shade_header *header); // [0..65535]
uint8_t shade_pisc_value_size_get(shade_header *header); // {0, 1, 2, 4}
uint32_t shade_pisc_get(shade_header *header);
uint8_t shade_pds_value_size_get(shade_header *header); // {0, 1, 2, 4}
uint8_t shade_pcs_value_size_get(shade_header *header); // {0, 1, 2, 4}
uint32_t shade_pcs_get(shade_header *header);

void shade_mode_set(shade_header *header, uint8_t mode);
uint32_t shade_payload_size_set(shade_header *header, uint32_t payload_byte_size);

void shade_pfc_set(shade_header *header, uint8_t pfc); //configure header first
uint8_t shade_psid_set(shade_header *header, uint8_t psid);
uint16_t shade_ptid_set(shade_header *header, uint16_t ptid);
uint32_t shade_pisc_set(shade_header *header, uint32_t pisc);
uint32_t shade_pcs_set(shade_header *header, uint32_t pcs);

void shade_payload_shade_version_set(shade_header *header);

#ifdef __cplusplus
}
#endif

#endif /* PROTOCOL_SHADE_H_ */
